language: rust

rust:
  - stable
  - beta
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

os: windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - language: python
      python: 3.7
      os: linux
      before_script:
        - pip install pre-commit
      script:
        - pre-commit run --all-files --show-diff-on-failure --config .travis-pre-commit-config.yaml

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo build
  - cargo test -- --test-threads 1
  - cargo fmt --all -- --check
  - cargo clippy --tests -- -D warnings
