[package]
name = "shawl"
version = "0.5.0"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Windows service wrapper for arbitrary commands"
repository = "https://github.com/mtkennerly/shawl"
readme = "README.md"
license = "MIT"

[dependencies]
ctrlc = "3.1.3"
flexi_logger = "0.15.1"
log = "0.4.8"
structopt = "0.3.2"
winapi = { version = "0.3.8", features = ["wincon"] }
windows-service = "0.2.0"

[dev-dependencies]
regex = "1.3.1"
speculate = "0.1.2"
