[package]
name = "shawl"
version = "1.4.0"
authors = ["mtkennerly <mtkennerly@gmail.com>"]
edition = "2018"
description = "Windows service wrapper for arbitrary commands"
repository = "https://github.com/mtkennerly/shawl"
readme = "README.md"
license = "MIT"
default-run = "shawl"

[dependencies]
clap = { version = "3.2.22", features = ["derive"] }
ctrlc = "3.4.1"
flexi_logger = "0.27.3"
log = "0.4.20"
winapi = { version = "0.3.9", features = ["wincon"] }
windows-service = "0.6.0"

[dev-dependencies]
regex = "1.10.2"
speculate = "0.1.2"

[build-dependencies]
winres = "0.1.12"
